### ISSUE TITLE
Unable to enable Kubeflow on fresh build

### ISSUE THREAD

**Issue by errorfixrepeat** [ubuntu/microk8s#1083]
I am having an issue where `microk8s enable kubeflow` doesn't progress past the `Waited  2475s for operator pods to come up, 15 remaining.` stages, with the remaining value fluctuating indefinitely (the lowest I've had is 2 remaining). It never reaches an error message even after >1 hour.

OS: Ubuntu 18.04.4 LTS Server with Ubuntu Desktop added (fresh install)
Hardware: AMD Ryzen 9 3900x, B450 chipset, NVIDIA 2080ti
Microk8s: v1.18.0    1293  latest/stable  canonical✓  classic

Inspect log
[inspection-report-20200401_211511.tar.gz](https://github.com/ubuntu/microk8s/files/4417425/inspection-report-20200401_211511.tar.gz)

DEBUG log from `enable kubeflow`
[enablekubeflowoutput.txt]
(https://github.com/ubuntu/microk8s/files/4417713/enablekubeflowoutput.txt)

Things I've tried:
- Allowing firewall access `sudo ufw allow in on cni0 && sudo ufw allow out on cni0` `sudo ufw default allow routed`
- Running deactivate and reactivate again.
- Installing older & latest edge versions.
   
I'd very much appreciate your help, or any pointers on how to resolve this issue, as I'm rather lost.

**Comment by ktsakalozos** [comment]
Hi @errorfixrepeat, we pushed a fix for this a few hours ago. Could you `sudo snap refresh microk8s --channel=stable` and retry the installation.

In https://github.com/ubuntu/microk8s/issues/1071 you can read more about the issue. There are some RBAC denials so the workaround for now is to disable RBAC.

**Comment by errorfixrepeat** [comment]
Apologies, I'm embarrased I missed that. The update seems to have stop the number bouncing up and down, but I am still unable to complete the enable hanging at 2 remaining.

microk8s  v1.18.0    1320  latest/stable  canonical✓  classic
[inspection-report-20200402_114751.tar.gz](https://github.com/ubuntu/microk8s/files/4420488/inspection-report-20200402_114751.tar.gz)
[microk8s enable kubeflow.txt](https://github.com/ubuntu/microk8s/files/4420496/microk8s.enable.kubeflow.txt)

Not sure if this is helpful, but I seem to have many pods initialising indefinitely:
[microk8s kubectl get all --all-namespaces .txt](https://github.com/ubuntu/microk8s/files/4420492/microk8s.kubectl.get.all.--all-namespaces.txt)

**Comment by knkski** [comment]
@errorfixrepeat: If you wait long enough (5-10m), does the process complete?

**Comment by VonRehberg** [comment]
Same here. It basically hangs on the two cert apps.
```
microk8s juju status -m uk8s:kubeflow
Model     Controller  Cloud/Region        Version  SLA          Timestamp
kubeflow  uk8s        microk8s/localhost  2.7.3    unsupported  12:37:57+02:00

App                          Version                         Status       Scale  Charm                        Store       Rev  OS          Address          Notes
ambassador                                                   active           1  ambassador                   jujucharms   78  kubernetes  192.168.178.205  
argo-controller                                              active           1  argo-controller              jujucharms  162  kubernetes                   
argo-ui                                                      active           1  argo-ui                      jujucharms   78  kubernetes  10.152.183.98    
cert-manager-controller                                      waiting          1  cert-manager-controller      jujucharms    9  kubernetes                   waiting for container
cert-manager-webhook                                         maintenance      1  cert-manager-webhook         jujucharms    9  kubernetes                   Waiting for secrets/cert-manager-webhook-tls to be created
dex-auth                                                     active           1  dex-auth                     jujucharms   20  kubernetes  10.152.183.155   
jupyter-controller                                           active           1  jupyter-controller           jujucharms  176  kubernetes                   
jupyter-web                                                  active           1  jupyter-web                  jujucharms   81  kubernetes  10.152.183.3     
katib-controller                                             active           1  katib-controller             jujucharms   76  kubernetes  10.152.183.139   
katib-db                     rocks.canonical.com:443/mar...  active           1  mariadb-k8s                  jujucharms   32  kubernetes  10.152.183.158   
katib-manager                                                active           1  katib-manager                jujucharms   75  kubernetes  10.152.183.190   
katib-ui                                                     active           1  katib-ui                     jujucharms   71  kubernetes  10.152.183.178   
kubeflow-dashboard                                           active           1  kubeflow-dashboard           jujucharms   36  kubernetes  10.152.183.84    
kubeflow-profiles                                            active           1  kubeflow-profiles            jujucharms   41  kubernetes  10.152.183.253   
metacontroller                                               active           1  metacontroller               jujucharms   68  kubernetes  10.152.183.156   
metadata-api                                                 active           1  metadata-api                 jujucharms   32  kubernetes  10.152.183.246   
metadata-db                  rocks.canonical.com:443/mar...  active           1  mariadb-k8s                  jujucharms   32  kubernetes  10.152.183.199   
metadata-envoy                                               active           1  metadata-envoy               jujucharms   14  kubernetes  10.152.183.179   
metadata-grpc                                                active           1  metadata-grpc                jujucharms   13  kubernetes  10.152.183.26    
metadata-ui                                                  active           1  metadata-ui                  jujucharms   34  kubernetes  10.152.183.205   
minio                                                        active           1  minio                        jujucharms   78  kubernetes  10.152.183.147   
modeldb-backend                                              active           1  modeldb-backend              jujucharms   76  kubernetes  10.152.183.130   
modeldb-db                   rocks.canonical.com:443/mar...  active           1  mariadb-k8s                  jujucharms   32  kubernetes  10.152.183.207   
modeldb-store                                                active           1  modeldb-store                jujucharms   69  kubernetes  10.152.183.56    
modeldb-ui                                                   active           1  modeldb-ui                   jujucharms   68  kubernetes  10.152.183.238   
oidc-gatekeeper                                              active           1  oidc-gatekeeper              jujucharms   19  kubernetes  10.152.183.89    
pipelines-api                                                active           1  pipelines-api                jujucharms   82  kubernetes  10.152.183.12    
pipelines-db                 rocks.canonical.com:443/mar...  active           1  mariadb-k8s                  jujucharms   32  kubernetes  10.152.183.184   
pipelines-persistence                                        active           1  pipelines-persistence        jujucharms  167  kubernetes                   
pipelines-scheduledworkflow                                  active           1  pipelines-scheduledworkflow  jujucharms  163  kubernetes                   
pipelines-ui                                                 active           1  pipelines-ui                 jujucharms   78  kubernetes  10.152.183.166   
pipelines-viewer                                             active           1  pipelines-viewer             jujucharms  102  kubernetes                   
pipelines-visualization                                      active           1  pipelines-visualization      jujucharms   13  kubernetes  10.152.183.144   
pytorch-operator                                             active           1  pytorch-operator             jujucharms  163  kubernetes                   
seldon-core                                                  active           1  seldon-core                  jujucharms   15  kubernetes  10.152.183.103   
tf-job-operator                                              active           1  tf-job-operator              jujucharms  159  kubernetes                   

Unit                            Workload     Agent  Address      Ports              Message
ambassador/0*                   active       idle   10.1.82.101  80/TCP             
argo-controller/0*              active       idle   10.1.82.165                     
argo-ui/0*                      active       idle   10.1.82.107  8001/TCP           
cert-manager-controller/0*      waiting      idle                                   waiting for container
cert-manager-webhook/0*         maintenance  idle                                   Waiting for secrets/cert-manager-webhook-tls to be created
dex-auth/1*                     active       idle   10.1.82.148  5556/TCP           
jupyter-controller/0*           active       idle   10.1.82.110                     
jupyter-web/0*                  active       idle   10.1.82.150  5000/TCP           
katib-controller/0*             active       idle   10.1.82.161  443/TCP            
katib-db/0*                     active       idle   10.1.82.145  3306/TCP           ready
katib-manager/0*                active       idle   10.1.82.147  6789/TCP           
katib-ui/0*                     active       idle   10.1.82.139  8000/TCP           
kubeflow-dashboard/0*           active       idle   10.1.82.163  8082/TCP           
kubeflow-profiles/0*            active       idle   10.1.82.149  8081/TCP           
metacontroller/0*               active       idle   10.1.82.133  9999/TCP           
metadata-api/0*                 active       idle   10.1.82.155  8080/TCP           
metadata-db/0*                  active       idle   10.1.82.152  3306/TCP           ready
metadata-envoy/0*               active       idle   10.1.82.127  9090/TCP,9091/TCP  
metadata-grpc/0*                active       idle   10.1.82.156  8080/TCP           
metadata-ui/0*                  active       idle   10.1.82.125  3000/TCP           
minio/0*                        active       idle   10.1.82.166  9000/TCP           
modeldb-backend/0*              active       idle   10.1.82.159  8085/TCP,8080/TCP  
modeldb-db/0*                   active       idle   10.1.82.154  3306/TCP           ready
modeldb-store/0*                active       idle   10.1.82.116  8086/TCP           
modeldb-ui/0*                   active       idle   10.1.82.158  3000/TCP           
oidc-gatekeeper/0*              active       idle   10.1.82.141  8080/TCP           
pipelines-api/0*                active       idle   10.1.82.171  8887/TCP,8888/TCP  
pipelines-db/0*                 active       idle   10.1.82.130  3306/TCP           ready
pipelines-persistence/0*        active       idle   10.1.82.168                     
pipelines-scheduledworkflow/0*  active       idle   10.1.82.119                     
pipelines-ui/0*                 active       idle   10.1.82.170  3000/TCP           
pipelines-viewer/0*             active       idle   10.1.82.129                     
pipelines-visualization/0*      active       idle   10.1.82.131  8888/TCP           
pytorch-operator/0*             active       idle   10.1.82.169                     
seldon-core/0*                  active       idle   10.1.82.137  8080/TCP,9876/TCP  
tf-job-operator/0*              active       idle   10.1.82.135                 
```

**Comment by OnTheRicky** [comment]
I'm not getting pass the following: 

ran `KUBEFLOW_DEBUG=true microk8s.enable kubeflow` and fails with the following:

Just trying to get a local kubeflow environment going with microk8s

Running: 
`macOS Catalina 10.15.4`
`multipass  1.1.0+mac`
`multipassd 1.1.0+mac`

> 17:52:06 DEBUG httpbakery client.go:243 client do GET https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/seldon-core-15/meta/any?include=id&include=supported-series&include=published {
17:52:07 DEBUG httpbakery client.go:245 } -> error <nil>
17:52:07 DEBUG juju.api monitor.go:35 RPC connection died
17:52:07 DEBUG juju.api monitor.go:35 RPC connection died
17:52:07 DEBUG juju.rpc server.go:328 error closing codec: write tcp 192.168.64.4:37816->10.152.183.80:17070: write: broken pipe
ERROR cannot deploy bundle: cannot add charm "cs:~kubeflow-charmers/seldon-core-15": connection is shut down
17:52:07 DEBUG cmd supercommand.go:519 error stack: 
/workspace/_build/src/github.com/juju/juju/rpc/client.go:14: connection is shut down
/workspace/_build/src/github.com/juju/juju/rpc/client.go:178: 
/workspace/_build/src/github.com/juju/juju/api/apiclient.go:1187: 
/workspace/_build/src/github.com/juju/juju/api/client.go:459: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/store.go:68: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:543: cannot add charm "cs:~kubeflow-charmers/seldon-core-15"
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:475: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:164: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/deploy.go:969: cannot deploy bundle
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/deploy.go:1540: 

>Command '('microk8s-juju.wrapper', '--debug', 'deploy', 'cs:kubeflow', '--channel', 'stable', '--overlay', '/tmp/tmp46o45t78')' returned non-zero exit status 1
Failed to enable kubeflow

>22:10:04 DEBUG juju.kubernetes.provider events.go:51 getting the latest event for "involvedObject.name=controller,involvedObject.kind=StatefulSet"
22:10:04 INFO  juju.juju api.go:302 API endpoints changed from [] to [10.152.183.231:17070]
22:10:04 INFO  cmd controller.go:89 Contacting Juju controller at 10.152.183.231 to verify accessibility...
22:10:04 INFO  juju.juju api.go:67 connecting to API addresses: [10.152.183.231:17070]
22:20:02 ERROR juju.cmd.juju.commands bootstrap.go:776 unable to contact api server after 1 attempts: unable to connect to API: dial tcp 10.152.183.231:17070: connect: connection refused
22:20:02 DEBUG juju.cmd.juju.commands bootstrap.go:777 (error details: [{/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/juju/common/controller.go:128: unable to contact api server after 1 attempts} {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/juju/common/controller.go:44: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/modelcommand.go:405: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/modelcommand.go:424: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/base.go:214: } {/build/juju/parts/juju/go/src/github.com/juju/juju/juju/api.go:72: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:207: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:622: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:967: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:1071: unable to connect to API} {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:1096: } {dial tcp 10.152.183.231:17070: connect: connection refused}])

**Comment by OnTheRicky** [comment]
same problem for me on macOS, latest versions, just hangs on last pod

**Comment by ktsakalozos** [comment]
@OnTheRicky @VonRehberg could you make sure you have RBAC disabled? Could you also please attach the `microk8s.inspect` tarball? Thank you.

**Comment by OnTheRicky** [comment]
@ktsakalozos I can confirm I triple checked. 
Even did a fresh install and checked again. 
Couldn't get it working, so removed the instance and unfortunately not able to get the `microk8s.inspect` tarball

**Comment by VonRehberg** [comment]
Hi @ktsakalozos 
Sure, RBAC was disabled. I attached the inspection file.
Thanks for investigating!
[inspection.tar.gz](https://github.com/ubuntu/microk8s/files/4455001/inspection.tar.gz)

**Comment by paravatha** [comment]
I am able to install successfully on Ubuntu **EC2** with this version (it takes a while for all the pods to come up, but they eventually come up after 30 mins)
I used this version
microk8s          v1.18.1    1341  candidate  canonical✓  classic

Congratulations, Kubeflow is now available.
The dashboard is available at http://10.64.140.43.xip.io/

Any idea, how I can setup proxy to access this dashboard via public EC2 ip?

**Comment by edoladin111** [comment]
@paravatha Did you figured this out ? I'm facing the same problem.

**Comment by knkski** [comment]
@paravatha, @edoladin111: See #713 for details of how to access the dashboard via EC2 IP address

**Comment by paravatha** [comment]
This issue is resolved #1140

**Comment by ktsakalozos** [comment]
Thank you all for your input. Feel free to reopen the issue if you feel it is not resolved.

**Comment by Jakubelo** [comment]
Hi, I am facing with the same problem of increasing and decreasing number of operator pods when `microk8s enable kubeflow` is running. I described issue here #1923
